- .gitignore
- requirements.txt
- sturdy/validator/reward.py
- tests/unit/validator/test_validator.py
> fix: invalid indexing of uids by validator

- setup.py
- sturdy/base/validator.py
- sturdy/constants.py
- sturdy/protocol.py
- sturdy/utils/config.py
- sturdy/utils/misc.py
- sturdy/utils/uids.py
- sturdy/validator/reward.py
- tests/unit/validator/test_validator.py
> Validator cheating fix and more

- README.md
- sturdy/base/miner.py
- sturdy/base/validator.py
- sturdy/utils/__init__.py
- sturdy/utils/config.py
- sturdy/utils/wandb.py
> Wandb Integration

- requirements.txt
d'oh - i keep forgetting to add reqs -_-
> chore: add wandb as a req

- requirements.txt
> chore: enforce wandb version

- sturdy/base/validator.py
- Logs miner scores from each validator
- Also logs validator iter step and the block it's synced up to.
> Feature: More Wandb Logs

- min_compute.yml
- sturdy/__init__.py
- sturdy/validator/reward.py
- tests/unit/validator/test_reward_helpers.py
- Refactored to seperate similarity matrix generation into its own function.
- Fix: Scale euclidean distance w.r.t. total assets available to the miner(s) to allocate to pools.
> Minor Refactor and Distance Scaling

- .gitignore
- abi/SturdyPair.json
- abi/SturdySiloStrategy.json
- abi/VariableInterestRate.json
- hardhat.config.js
- neurons/validator.py
- sturdy/pools.py
- sturdy/validator/forward.py
- sturdy/validator/reward.py
- tests/unit/validator/test_pool_models.py
- Adds support for Sturdy Finance silos.
> Sturdy Silo Support

- abi/Pot.json
- abi/SavingsDai.json
- sturdy/algo.py
- sturdy/pools.py
- sturdy/validator/reward.py
- tests/unit/validator/test_pool_models.py
- Adds support for dai savings rate token.
> Dai Savings Rate Support

- abi/Comet.json
- abi/EACAggregatorProxy.json
- abi/FeedRegistry.json
- sturdy/algo.py
- sturdy/pools.py
- sturdy/validator/reward.py
- tests/unit/validator/test_pool_models.py
- Adds support for compound finance V3 pool model.
> Compound V3 Support

- db/migrations/20240725003510_allocations.sql
- db/sql.py
- neurons/validator.py
- sturdy/protocol.py
- sturdy/validator/forward.py
- Adds support for users to obtain data regarding allocations which the validator has received through the `/get_allocations/` and `/request_info/` endpoints.
> Allocation Data DB

- sturdy/validator/reward.py
- tests/unit/validator/test_reward_helpers.py
The updated normalization function computes z-scores based on the gradients between consecutive APYs to identify significant deviations in value. These z-scores help filter out APYs that exceed the specified z-score threshold, focusing on candidates below a given quantile. This filtered set is used to determine the lower bound for clipping, ensuring that extremely low-scoring outlier miners are filtered out as noise to produce a more pronounced incentive curve for more productive miners.
> feat: updated normalization technique

- sturdy/validator/forward.py
shuffle active uids, for example:
before shuffle: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', …
> shuffle active uids

- db/migrations/20241030231410_alloc_table.sql
- min_compute.yml
- neurons/validator.py
- requirements-dev.txt
- sturdy/__init__.py
- sturdy/constants.py
- sturdy/validator/reward.py
- tests/unit/validator/test_reward_helpers.py
- fixes a float overflow error in `get_distance`
- fix typo in sql migration script.
- decreases frequency of `"Running synthetic vali..."` debug message to avoid flooding logs.
> Release 2.0.1

- neurons/validator.py
- sturdy/pools.py
- sturdy/validator/forward.py
- sturdy/validator/reward.py
- tests/unit/validator/test_pool_models.py
- tests/unit/validator/test_reward_helpers.py
- fixes yield calculation
- renaming share price and normalized income (from aave pools) to "yield index" for consistency.
> fix: yield calculation + rename share price to yield index

- convert_state.py
how to run fix:
```
pip install numpy==1.26.4
python convert_state.py --wallet.name NAME --wallet.hotkey HOTKEY --netuid 10
pip install -r requirements.txt
pip install -e .
```
> fix: add script to convert states from torch to numpy

- min_compute.yml
- neurons/validator.py
- sturdy/__init__.py
- sturdy/base/validator.py
- bump to 2.2.1 + async fix + update API key validation paths
> Release 2.2.1

- docs/miner.md
- docs/validator.md
- min_compute.yml
- neurons/validator.py
- requirements.txt
- sturdy/__init__.py
- sturdy/base/miner.py
- sturdy/base/neuron.py
- sturdy/base/validator.py
- sturdy/constants.py
- sturdy/utils/config.py
- sturdy/utils/wandb.py
- sturdy/validator/forward.py
- tests/unit/validator/test_pool_models.py
- tests/unit/validator/test_reward_helpers.py
- there's no point in having a "synthetic" validator - just makes code more complicated with no real upside. removed. every validator is now an "organic" validator.
- added minimum total assets requirement for both synthetic and organic requests.
- modified some unit tests
- context management fix for default miner
> Release 2.2.4

- min_compute.yml
- sturdy/__init__.py
- sturdy/constants.py
- sturdy/validator/apy_binning.py
- sturdy/validator/reward.py
- tests/unit/validator/test_reward_helpers.py
applying larger bonuses to top performers
> Release 2.2.9

- .dockerignore
- .github/docker.yml
- .gitignore
- Dockerfile
- docker-compose.yml
- docker-entrypoint.sh
This pull request introduces Docker support for the project, including a Dockerfile, a Compose setup with [Watchtower](https://github.com/containrrr/watchtower), and CI/CD integration for building and publishing Docker images. The changes streamline deployment and ensure better environment consistency.
> Dockerize Validator with Watchtower

- min_compute.yml
- neurons/validator.py
- sturdy/__init__.py
- sturdy/constants.py
- sturdy/utils/bt_alpha.py
- sturdy/validator/apy_binning.py
- sturdy/validator/reward.py
- tests/unit/validator/test_reward_helpers.py
- better error messages + return statements
- bring back top performer bonus
- fixed method of getting nominator stake - we use TotalHotkeyAlpha now
- the delta amount that we pass into get_vali_avg_apy should be in
alpha, not TAO
- set `TOP_PERFORMER_BONUS` to 2.0 for now
> Release 3.0.9

- min_compute.yml
- requirements.txt
- sturdy/__init__.py
- sturdy/validator/reward.py
This fixes the way `alpha_lost` is calculated.
> fix: correct alpha lost calculation

- min_compute.yml
- sturdy/__init__.py
- sturdy/validator/reward.py
- error handles if token id invalid
> fix: position id error

- min_compute.yml
- sturdy/__init__.py
- sturdy/validator/reward.py
> fix: noisy times log

- min_compute.yml
- sturdy/__init__.py
- sturdy/validator/reward.py
- check if swap is within position tick range.
- normalize lp rewards correctly
> fix: uniswap fees bug

- sturdy/validator/sql.py
the way the garbage collection works for the `allocations` table in the validator's database is wrong - we're currently garbage collection `allocations` from the `latest_creation_date` of the set of `active_allocs` we garbage collect. this is bad because there may be some allocations that were created earlier that would be erased too. this pr addresses this problem
> fix: don't collect non-garbage stuff
