.gitignore
neurons/validator.py
sturdy/base/validator.py

The synthetic validator loop would not execute correctly if run by itself.

fix: synthetic validator looping issue fixed

---

requirements.txt
sturdy/base/neuron.py

- Bumped bittensor version to 6.11.0
- Bittensor >=6.10.0 introduced some changes to their logging infra so I had to accomodate for that (see commits)

Logging workaround + Bump Version

---

sturdy/__init__.py
sturdy/base/validator.py
sturdy/utils/config.py
sturdy/utils/wandb.py

This updates adds support for rolling over (reinitializing) wandb runs automatically after a certain number of logs have been made. This has been done as a workaround to what appears to be a ~100K log line limit on wandb.

hotfix: wandb rollover after certain number of wandb logs

---

requirements.txt

the latest version of numpy (2.0.0) which was released today is breaking `wandb==0.17.0` package, need to install the previous version of numpy to get it fixed
the exception itself is
```
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use 
`np.float64` instead.
/root/sturdy-subnet/myenv/lib/python3.10/site-packages/eth_utils/network.py:44: UserWarning: Network 345 with name 'Yooldo Verse Mainnet' does not have a valid ChainId. eth-typing should be updated with the latest networks.
warnings.warn(
/root/sturdy-subnet/myenv/lib/python3.10/site-packages/eth_utils/network.py:44: UserWarning: Network 12611 with name 'Astar zkEVM' does not have a valid ChainId. eth-typing should be updated with the latest networks.
warnings.warn(
╭───────────────────── Traceback (most recent …
```

fixed numpy version

---

min_compute.yml
sturdy/__init__.py
sturdy/validator/simulator.py

- Fixed simulator rate change calculation. Originally assumed that reversion speed was in units of wei when it was in fact not.

Hotfix: Simulator Rate Change Calculation

---

README.md
docs/validator.md
neurons/validator.py
requirements.txt
sturdy/algo.py
sturdy/pools.py
sturdy/protocol.py
sturdy/utils/misc.py
sturdy/validator/reward.py
sturdy/validator/simulator.py
tests/integration/validator/test_integration_validator.py
tests/unit/validator/test_pool_generator.py
tests/unit/validator/test_pool_models.py
tests/unit/validator/test_simulator.py
tests/unit/validator/test_validator.py

We now use contract addresses instead of pool ids for to index allocation values. This has basically been done so that the responses of the subnet is translatable into a more suitable format for on-chain requests via an airnode.

Updated Spec - Use Contract Addresses In Place Of Pool IDs

---

requirements.txt
sturdy/validator/reward.py
tests/unit/validator/test_reward_helpers.py

As reported by @quynhvu4180 [here](https://canary.discord.com/channels/799672011265015819/1217952256306057298/1296318077964648489), attempting to calculate the distance between allocations (numpy arrays) with large numbers results in overflow. This patch introduces `gmpy2` for arbitrary precision arithmetic to serve as a workaround for this issue.

fix: workaround for large integer overflow w/ numpy

---

sturdy/constants.py
sturdy/validator/reward.py
tests/unit/validator/test_reward_helpers.py

Hey @Shr1ftyy @sforman2000,
As described in the issue #63, the subnet churns out high APY miners for low latency miners in large proportions (75%), participating in the flattening of the incentive curve.  This PR addresses the core issue while meeting the initial concerns for cheating / relay mining.
Updates: 
-  Adds an APY similarity matrix
-  Increase penalties calculation sensitivity by decreasing thresholds to match allocation/ apy precision 
-  Update penalties computation to be based on allocation, APY and latency

fix: Remove reward model distortions

---

min_compute.yml
requirements.txt
sturdy/__init__.py
sturdy/base/neuron.py
sturdy/base/validator.py
sturdy/utils/config.py
sturdy/validator/reward.py

fix: non-responsive uids shouldn't get big scores
- using `zeros_like` because `empty_like` uses big placeholder nums.
- allocations should not be None AND be responsive
- logging fix

Release 2.1.4

---

sturdy/base/validator.py
sturdy/utils/config.py
sturdy/validator/forward.py
sturdy/validator/request.py
sturdy/validator/utils/axon.py

**Background**
When Validators score Miners, response time is a critical metric. However, there is a significant issue in the current process where the calculation of miner response time is adversely affected by blocking delays on the Validator side:
- The process of sending requests experiences blocking, and the blocked time is inadvertently included in the calculated axon_time.
- Miners that are delayed due to this blocking are penalized with an increased axon_time, which affects their similarity score.
- Although the UIDs are randomly shuffled during task dispatch (see [PR #66](https://github.com/Sturdy-Subnet/sturdy-subnet/pull/66)), this does not mitigate the unfair impact on individual miners. We strongly recommend following the approach used in the subnet …

 Fix bug in calculating miner response time

---

min_compute.yml
sturdy/__init__.py
sturdy/algo.py
sturdy/base/validator.py
sturdy/constants.py
sturdy/validator/apy_binning.py
sturdy/validator/reward.py
tests/unit/validator/test_reward_helpers.py

This update introduces a change to the incentive mechanism.
Here's a brief breakdown of the changes that will be introduced
1. Firstly, when before scoring, miners will be grouped into bins based on their APY (the ranges for each these bins may be determined automatically)
2. Then, score the miners based on their APY
3. and then penalize miners who have similar allocations to other miners *within each APY group*.
This would effectively remove the need for the current APY similarity checking mechanism. 
To add to the steps above, another step (either after 2 or 3) which involves performing some sort of operation that would make it so that the top few miners (or even, just the top miner) receive an outsized reward vs. the rest of the miners in the subnet. I think this makes sense as the …

Release 2.2.8

---

min_compute.yml
sturdy/__init__.py
sturdy/constants.py
sturdy/validator/apy_binning.py
tests/unit/validator/test_reward_helpers.py

This pull request adds support for a dynamic bin threshold, calculated using the coefficient of variation (CV).
The coefficient of variation measures how spread out the APY values are relative to their mean. It’s a scale-independent metric, which makes it well-suited for adapting bin thresholds across different APY distributions — whether values are large or small.
This solution would also work well with alpha token pools on Bittensor.

Add dynamic bin threshold

---

.env.example
min_compute.yml
neurons/validator.py
sturdy/__init__.py
sturdy/constants.py

- Increased scoring period range from 12 to 24 hours.
- Dockerized validator, and also hooked it up to watchtower for auto-updating functionality (#100)

Release 3.0.3

---

docs/api_usage.md
min_compute.yml
neurons/validator.py
sturdy/__init__.py
sturdy/algo.py
sturdy/pools.py
sturdy/protocol.py
sturdy/utils/bt_alpha.py
sturdy/utils/misc.py
sturdy/validator/forward.py
sturdy/validator/reward.py

- account for current allocations across bittensor alpha token pools
- consider slippage given current allocations
- updated `/allocate_bt` endpoint to account for the above
- updated api usage docs

Release 3.0.4

---

docs/validator.md
min_compute.yml
sturdy/__init__.py
sturdy/base/validator.py
sturdy/utils/bt_alpha.py
sturdy/utils/config.py

- validator axon no longer gets served - it's not necessary
- remove ttl parameters for alpha pool helpers
- updated docs for docker

Release 3.0.8

---

min_compute.yml
sturdy/__init__.py
sturdy/validator/apy_binning.py
tests/unit/validator/test_reward_helpers.py

instead of:
```python
relative_diff = abs(apy - current_base_apy) / max(abs(current_base_apy), abs(apy), 1)
```
we calculate it as:
```python
relative_diff = float("inf") if apy == 0 else abs((current_base_apy - apy) / apy)
```
as we want to compare the relative difference in reference to the apy we are *currently* examining in the loop to help determine whether if it should be in a different bin vs. that of which contains `current_base_apy`.

fix: relative diff based on current apy

---

min_compute.yml
sturdy/__init__.py
sturdy/validator/forward.py
sturdy/validator/reward.py

- this fix makes it so that a validator will skip updating scores if all miners have zero apy.

fix: zero apy skip

---

min_compute.yml
sturdy/__init__.py
sturdy/validator/reward.py

If delta < 0, tao_lost_bal results in a decrease in total assets.
So when calculate total_yield, consider this tao loss.

fix calculation of alpha_lost and total_yield in case of delta<0

---

min_compute.yml
sturdy/__init__.py
sturdy/base/validator.py

using the same synapse object results in all the miners being considered as being a part of the same group (uniswap lp or pool allocator). this is bad. we now copy the synapse for each request instead of referring to the same one.
python moment `(._.)`

fix: dont refer to same synapse

---

min_compute.yml
sturdy/__init__.py
sturdy/utils/taofi_subgraph.py
sturdy/validator/reward.py

When a position NFT gets burnt, the deposited liquidity associated with the position gets considered as uncollected fees: 
https://github.com/Uniswap/v3-core/blob/main/contracts/UniswapV3Pool.sol#L535-L540
This obviously shouldn't be considered as fees in our calculation, because it's really just the deposited liquidity for the position.

fix: filter amounts from burn events

---

pyproject.toml
swap/__init__.py
swap/base/neuron.py
swap/utils/taofi_subgraph.py
uv.lock

Both burns and DecreaseLiquidity amounts should be subtracted from uncollected fees separately, not adjusted against each other. The previous logic allowed miners to game the system by creating positions and immediately decreasing liquidity, which would cancel out the burn and count as fees.
- remove calculate_adjusted_burn_amounts() function
- subtract burns and DecreaseLiquidity amounts independently
- prevent miners from gaming fees by liquidity manipulation

fix: prevent gaming via DecreaseLiquidity events
